timezone: Asia/Tokyo
safe: true
theme: jekyll-theme-minimal
google_analytics: UA-185571-3
url: https://seagull-kamome.github.io/
plugins:
    - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

